services:
  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    container_name: homeassistant
    restart: always
    environment:
      - TZ=Asia/Seoul
      - /etc/localtime:/etc/localtime:ro
    volumes:
      - ./.homeassistant:/config
    privileged: true
    network_mode: host

  esphome:
    container_name: esphome
    image: ghcr.io/esphome/esphome
    volumes:
      - ./.esphome:/config
      - /etc/localtime:/etc/localtime:ro
    restart: always
    privileged: true
    network_mode: host
    environment:
      - USERNAME=root
      - PASSWORD=dlgksdud
